# Generated by Django 5.2.9 on 2025-12-19 03:36

import accounts.managers
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_last_lo_8c3951_idx',
            old_name='accounts_us_last_lo_3b1484_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_acti_a5841d_idx',
            old_name='accounts_us_is_act_4ef7b3_idx',
        ),
        migrations.RenameIndex(
            model_name='usercode',
            new_name='accounts_us_user_id_7bfdc0_idx',
            old_name='accounts_us_user_i_11b38c_idx',
        ),
        migrations.RenameIndex(
            model_name='usercodeallowedstate',
            new_name='accounts_us_state_baaff2_idx',
            old_name='accounts_us_state__fc4a74_idx',
        ),
        migrations.RenameIndex(
            model_name='userroleassignment',
            new_name='accounts_us_role_id_e09d8f_idx',
            old_name='accounts_us_role_i_39c574_idx',
        ),
        migrations.RenameIndex(
            model_name='usertotpdevice',
            new_name='accounts_us_user_id_079a55_idx',
            old_name='accounts_us_user_i_27c326_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='days_of_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(127)]),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='pin_length',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_ci_unique'),
        ),
    ]
