# Generated by Django 5.2.9 on 2025-12-26 01:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_hash', models.TextField()),
                ('label', models.CharField(blank=True, max_length=150)),
                ('code_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('one_time', 'One-time'), ('service', 'Service')], max_length=16)),
                ('pin_length', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)])),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('days_of_week', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(127)])),
                ('window_start', models.TimeField(blank=True, null=True)),
                ('window_end', models.TimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_lock', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'door_codes',
            },
        ),
        migrations.CreateModel(
            name='DoorCodeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lock_entity_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('code_used', 'Code Used'), ('code_failed', 'Code Failed'), ('code_synced', 'Code Synced'), ('code_removed', 'Code Removed'), ('code_created', 'Code Created'), ('code_updated', 'Code Updated'), ('code_deleted', 'Code Deleted')], max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('door_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locks.doorcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_code_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'door_code_events',
            },
        ),
        migrations.CreateModel(
            name='DoorLock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('supports_code_slots', models.BooleanField(default=False)),
                ('max_code_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'door_locks',
                'indexes': [models.Index(fields=['is_available'], name='door_locks_is_avai_218e91_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoorCodeLockAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lock_entity_id', models.CharField(max_length=255)),
                ('code_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('door_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_assignments', to='locks.doorcode')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_assignments', to='locks.doorlock')),
            ],
            options={
                'db_table': 'door_code_lock_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='doorcode',
            index=models.Index(fields=['user'], name='door_codes_user_id_bc5085_idx'),
        ),
        migrations.AddIndex(
            model_name='doorcode',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['user'], name='door_codes_active_user_idx'),
        ),
        migrations.AddIndex(
            model_name='doorcode',
            index=models.Index(condition=models.Q(('end_at__isnull', False)), fields=['end_at'], name='door_codes_end_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='doorcode',
            constraint=models.CheckConstraint(condition=models.Q(('pin_length__gte', 4), ('pin_length__lte', 8)), name='door_codes_pin_length_between_4_8'),
        ),
        migrations.AddConstraint(
            model_name='doorcode',
            constraint=models.CheckConstraint(condition=models.Q(('days_of_week__isnull', True), models.Q(('days_of_week__gte', 0), ('days_of_week__lte', 127)), _connector='OR'), name='door_codes_days_of_week_between_0_127'),
        ),
        migrations.AddConstraint(
            model_name='doorcode',
            constraint=models.CheckConstraint(condition=models.Q(('uses_count__gte', 0)), name='door_codes_uses_count_gte_0'),
        ),
        migrations.AddIndex(
            model_name='doorcodeevent',
            index=models.Index(fields=['door_code', 'created_at'], name='door_code_e_door_co_a7d4af_idx'),
        ),
        migrations.AddIndex(
            model_name='doorcodeevent',
            index=models.Index(fields=['event_type', 'created_at'], name='door_code_e_event_t_cb525b_idx'),
        ),
        migrations.AddIndex(
            model_name='doorcodeevent',
            index=models.Index(fields=['user', 'created_at'], name='door_code_e_user_id_8ac1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='doorcodelockassignment',
            index=models.Index(fields=['lock_entity_id'], name='door_code_l_lock_en_8e1d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='doorcodelockassignment',
            index=models.Index(fields=['sync_status'], name='door_code_l_sync_st_3b72a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='doorcodelockassignment',
            constraint=models.UniqueConstraint(fields=('door_code', 'lock_entity_id'), name='door_code_lock_assignments_unique_code_lock'),
        ),
    ]
