# Generated by Django 5.2.9 on 2025-12-26 00:00

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="doorcodelockassignment",
            name="door_code_l_sync_st_3b72a0_idx",
        ),
        migrations.RemoveField(
            model_name="doorcodelockassignment",
            name="lock",
        ),
        migrations.RemoveField(
            model_name="doorcodelockassignment",
            name="code_slot",
        ),
        migrations.RemoveField(
            model_name="doorcodelockassignment",
            name="sync_status",
        ),
        migrations.RemoveField(
            model_name="doorcodelockassignment",
            name="last_synced_at",
        ),
        migrations.RemoveField(
            model_name="doorcodelockassignment",
            name="sync_error",
        ),
        migrations.DeleteModel(
            name="DoorLock",
        ),
    ]
