# Generated by Django 5.2.9 on 2025-12-19 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettingsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('delay_time', models.PositiveIntegerField(default=60)),
                ('arming_time', models.PositiveIntegerField(default=60)),
                ('trigger_time', models.PositiveIntegerField(default=120)),
                ('disarm_after_trigger', models.BooleanField(default=False)),
                ('code_arm_required', models.BooleanField(default=True)),
                ('available_arming_states', models.JSONField(blank=True, default=list)),
                ('state_overrides', models.JSONField(blank=True, default=dict)),
                ('audio_visual_settings', models.JSONField(blank=True, default=dict)),
                ('sensor_behavior', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='alarm_alarm_is_acti_175de8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_delay_override', models.PositiveIntegerField(blank=True, null=True)),
                ('active_states', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='alarm_zone_is_acti_c95f45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_entry_point', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='alarm.zone')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('armed', 'Armed'), ('disarmed', 'Disarmed'), ('pending', 'Pending'), ('triggered', 'Triggered'), ('code_used', 'Code used'), ('sensor_triggered', 'Sensor triggered'), ('failed_code', 'Failed code'), ('state_changed', 'State changed')], max_length=32)),
                ('state_from', models.CharField(blank=True, choices=[('disarmed', 'Disarmed'), ('arming', 'Arming'), ('armed_home', 'Armed home'), ('armed_away', 'Armed away'), ('armed_night', 'Armed night'), ('armed_vacation', 'Armed vacation'), ('pending', 'Pending'), ('triggered', 'Triggered')], max_length=32, null=True)),
                ('state_to', models.CharField(blank=True, choices=[('disarmed', 'Disarmed'), ('arming', 'Arming'), ('armed_home', 'Armed home'), ('armed_away', 'Armed away'), ('armed_night', 'Armed night'), ('armed_vacation', 'Armed vacation'), ('pending', 'Pending'), ('triggered', 'Triggered')], max_length=32, null=True)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='accounts.usercode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='alarm.sensor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='alarm.zone')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('disarmed', 'Disarmed'), ('arming', 'Arming'), ('armed_home', 'Armed home'), ('armed_away', 'Armed away'), ('armed_night', 'Armed night'), ('armed_vacation', 'Armed vacation'), ('pending', 'Pending'), ('triggered', 'Triggered')], max_length=32)),
                ('previous_state', models.CharField(blank=True, choices=[('disarmed', 'Disarmed'), ('arming', 'Arming'), ('armed_home', 'Armed home'), ('armed_away', 'Armed away'), ('armed_night', 'Armed night'), ('armed_vacation', 'Armed vacation'), ('pending', 'Pending'), ('triggered', 'Triggered')], max_length=32, null=True)),
                ('target_armed_state', models.CharField(blank=True, choices=[('disarmed', 'Disarmed'), ('arming', 'Arming'), ('armed_home', 'Armed home'), ('armed_away', 'Armed away'), ('armed_night', 'Armed night'), ('armed_vacation', 'Armed vacation'), ('pending', 'Pending'), ('triggered', 'Triggered')], max_length=32, null=True)),
                ('entered_at', models.DateTimeField()),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('last_transition_reason', models.CharField(blank=True, max_length=64)),
                ('timing_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_transition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_transitions', to=settings.AUTH_USER_MODEL)),
                ('settings_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_snapshots', to='alarm.alarmsettingsprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['current_state'], name='alarm_alarm_current_a2c960_idx'), models.Index(fields=['exit_at'], name='alarm_alarm_exit_at_0704c8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['zone', 'is_active'], name='alarm_senso_zone_id_0d401e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='sensors_zone_name'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='alarm_alarm_event_t_d7f682_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['state_to'], name='alarm_alarm_state_t_bd79c2_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['timestamp'], name='alarm_alarm_timesta_49d37c_idx'),
        ),
        migrations.AddConstraint(
            model_name='alarmevent',
            constraint=models.CheckConstraint(condition=models.Q(('timestamp__isnull', False)), name='alarm_events_timestamp_not_null'),
        ),
    ]
