# Generated by Django 5.2.9 on 2025-12-20 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_alarm_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('device_class', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('last_state', models.CharField(blank=True, max_length=255, null=True)),
                ('last_changed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='entities', to='alarm.entitytag')),
            ],
            options={
                'ordering': ['entity_id'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('trigger', 'Trigger'), ('disarm', 'Disarm'), ('arm', 'Arm'), ('suppress', 'Suppress'), ('escalate', 'Escalate')], db_index=True, max_length=32)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('cooldown_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField()),
                ('kind', models.CharField(blank=True, choices=[('trigger', 'Trigger'), ('disarm', 'Disarm'), ('arm', 'Arm'), ('suppress', 'Suppress'), ('escalate', 'Escalate')], max_length=32)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('trace', models.JSONField(blank=True, default=dict)),
                ('alarm_state_before', models.CharField(blank=True, max_length=32)),
                ('alarm_state_after', models.CharField(blank=True, max_length=32)),
                ('error', models.TextField(blank=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm.entity')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm.rule')),
            ],
            options={
                'ordering': ['-fired_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RuleEntityRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_refs', to='alarm.entity')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_refs', to='alarm.rule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('satisfied', 'Satisfied'), ('cooldown', 'Cooldown')], default='pending', max_length=32)),
                ('became_true_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_states', to='alarm.rule')),
            ],
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['domain'], name='alarm_entit_domain_e7e04b_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['enabled', 'kind', '-priority'], name='alarm_rule_enabled_9cb288_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleactionlog',
            index=models.Index(fields=['fired_at'], name='alarm_rulea_fired_a_79507d_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleactionlog',
            index=models.Index(fields=['kind', 'fired_at'], name='alarm_rulea_kind_cce35e_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleentityref',
            index=models.Index(fields=['entity', 'rule'], name='alarm_rulee_entity__270764_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleentityref',
            constraint=models.UniqueConstraint(fields=('rule', 'entity'), name='rule_entity_ref_unique'),
        ),
        migrations.AddIndex(
            model_name='ruleruntimestate',
            index=models.Index(fields=['rule', 'node_id'], name='alarm_ruler_rule_id_f90ef4_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleruntimestate',
            constraint=models.UniqueConstraint(fields=('rule', 'node_id'), name='rule_node_unique'),
        ),
    ]
