# Generated by Django 5.2.9 on 2025-12-22 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_remove_sensor_zone_remove_alarmevent_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('json', 'JSON')], max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_config_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='alarm_syste_key_5a0c88_idx'), models.Index(fields=['value_type'], name='alarm_syste_value_t_a29ded_idx')],
            },
        ),
    ]
