# Generated by Django 5.2.9 on 2025-12-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_systemconfig'),
    ]

    def _seed_entries(apps, schema_editor):
        AlarmSettingsProfile = apps.get_model("alarm", "AlarmSettingsProfile")
        AlarmSettingsEntry = apps.get_model("alarm", "AlarmSettingsEntry")

        for profile in AlarmSettingsProfile.objects.all():
            def upsert(key: str, value_type: str, value):
                AlarmSettingsEntry.objects.update_or_create(
                    profile=profile,
                    key=key,
                    defaults={"value_type": value_type, "value": value},
                )

            upsert("delay_time", "integer", profile.delay_time)
            upsert("arming_time", "integer", profile.arming_time)
            upsert("trigger_time", "integer", profile.trigger_time)
            upsert("disarm_after_trigger", "boolean", profile.disarm_after_trigger)
            upsert("code_arm_required", "boolean", profile.code_arm_required)
            upsert("available_arming_states", "json", profile.available_arming_states)
            upsert("state_overrides", "json", profile.state_overrides)
            upsert("audio_visual_settings", "json", profile.audio_visual_settings)
            upsert("sensor_behavior", "json", profile.sensor_behavior)

    operations = [
        migrations.CreateModel(
            name='AlarmSettingsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('json', 'JSON')], max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='alarm.alarmsettingsprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'key'], name='alarm_alarm_profile_500b55_idx'), models.Index(fields=['key'], name='alarm_alarm_key_9007be_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'key'), name='alarm_settings_entries_unique_profile_key')],
            },
        ),
        migrations.RunPython(_seed_entries, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='arming_time',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='audio_visual_settings',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='available_arming_states',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='code_arm_required',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='delay_time',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='disarm_after_trigger',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='sensor_behavior',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='state_overrides',
        ),
        migrations.RemoveField(
            model_name='alarmsettingsprofile',
            name='trigger_time',
        ),
    ]
