# Generated by Django 5.2.9 on 2025-12-22 00:00

from __future__ import annotations

from django.db import migrations


def _seed_exit_delay_overrides(apps, schema_editor):
    AlarmSettingsProfile = apps.get_model("alarm", "AlarmSettingsProfile")
    AlarmSettingsEntry = apps.get_model("alarm", "AlarmSettingsEntry")

    defaults = {
        "armed_home": {"arming_time": 0},
        "armed_night": {"arming_time": 10},
        "armed_away": {"arming_time": 60},
        "armed_vacation": {"arming_time": 60},
    }

    for profile in AlarmSettingsProfile.objects.all():
        entry, _created = AlarmSettingsEntry.objects.get_or_create(
            profile=profile,
            key="state_overrides",
            defaults={"value_type": "json", "value": defaults},
        )
        value = entry.value if isinstance(entry.value, dict) else {}

        changed = False
        for state, override in defaults.items():
            existing = value.get(state)
            if not isinstance(existing, dict):
                value[state] = dict(override)
                changed = True
                continue
            if "arming_time" not in existing:
                existing["arming_time"] = override["arming_time"]
                value[state] = existing
                changed = True

        if changed:
            entry.value = value
            entry.value_type = "json"
            entry.save(update_fields=["value", "value_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("alarm", "0006_remove_alarmsettingsprofile_arming_time_and_more"),
    ]

    operations = [
        migrations.RunPython(_seed_exit_delay_overrides, reverse_code=migrations.RunPython.noop),
    ]

